### PR TITLE
feat: 🎸 add support of vue 3 based on heroicons code

### PR DESCRIPTION
**Pull request by b-barry**
Add new format for vue 3 that remove the need of transformIgnorePatterns
in jest for example. Everything is compiled and common js ready

### CODE REVIEW

**Comment by daniarsuprianto** [comment]
I guess we need vue3 to test this. Does this one of those PR to only prepare for the future case or it has to be merged now?

**Comment by messenjer** [comment]
@daniarsuprianto yes, this is an implementation to have better support with vue3.

With that, we can use the icons in a new funda project using vue3.

```diff
-import { Alert as AlertIcon } from "@funda/icons/lib/vue"; 
+import { Alert as AlertIcon } from "@funda/icons/lib/vue3";
```

And remove some specific rules in the `jest.config.js` 

```diff
-transformIgnorePatterns: ['/node_modules/(?!@funda/icons)'],
```

Normally, this change does not affect projects already using "@funda/icons", and could therefore be merged.

May be, we can add also information about support vue3 in the `README.md`

> ### Vue3 import
> 
> ```js
> import { ThumbsDown } from "@funda/icons/lib/vue3";
> import Alert from "@funda/icons/lib/vue3/alert";
> 
> export default {
>     ...,
>     components: { ThumbsDown }
>     ...,
> }
> ```

**Comment by messenjer** [comment]
@daniarsuprianto I added the information about support vue3 in the `README.md`

**Comment by messenjer** [comment]
Hello @daniarsuprianto, could we merge next week this pull request? It's also fix an issue with Nuxt3 app.

**Comment by daniarsuprianto** [comment]
> Hello @daniarsuprianto, could we merge next week this pull request? It's also fix an issue with Nuxt3 app.

Hey @messenjer sorry for taking so long..
Yes sure.. i dont see any breaking change here, so let's do that :)

**Review by daniarsuprianto — APPROVED** [review]

**Comment by messenjer** [comment]
Hello @daniarsuprianto, there was a problem with the deployment.

```
Run peaceiris/actions-gh-pages@v3
[INFO] Usage https://github.com/peaceiris/actions-gh-pages#readme
Dump inputs
Setup auth token
  Error: Action failed with "not found deploy key or tokens"
```

Screenshot 2021-12-20 at 09 32 09

Can you look at this?

**Comment by jpsc** [comment]
> Hello @daniarsuprianto, there was a problem with the deployment.
> 
> https://github.com/funda-frontend/icons/runs/4561895618?check_suite_focus=true
> 
> ```
> Run peaceiris/actions-gh-pages@v3
> [INFO] Usage https://github.com/peaceiris/actions-gh-pages#readme
> Dump inputs
> Setup auth token
>   Error: Action failed with "not found deploy key or tokens"
> ```
> 
> Screenshot 2021-12-20 at 09 32 09
> 
> Can you look at this?

cc @dine

**Comment by messenjer** [comment]
Hi @dine, I added the commit from your PR.

**Comment by dine** [comment]
Well, it adds an approval step, but then the token has read only access 😒

Screenshot 2021-12-20 at 14 09 37

Screenshot 2021-12-20 at 14 13 45

Gonna add your changes to the branch PR so we can get unblocked.

**Comment by dine** [comment]
@b-barry added your changes to the other PR https://github.com/funda-frontend/icons/pull/295

**Comment by jpsc** [comment]
This was merged with #295

**Pull request closed without merging**
