### PR TITLE
feat(icon): add grip and crop icons

### PR DESCRIPTION
**Pull request by bartderijk**
I'm replacing the old icon component for the new office page cms in funda desk and found these icons were missing.

### CODE REVIEW

**Review by daniarsuprianto — APPROVED** [review]

**Review by jpsc — CHANGES_REQUESTED** [review]
I would remove the svg id's attr from both. They are not required.

**Comment by daniarsuprianto** [comment]
> I would remove the svg id's attr from both. They are not required.

i think it will be sanitized no? im not sure anymore

**Comment by bartderijk** [comment]
> I would remove the svg id's attr from both. They are not required.

Fixed!

**Comment by larsdouweschuitema** [comment]
There is a nice tool which reduces size of SVG: https://jakearchibald.github.io/svgomg/
Maybe you already used it, but it can't hurt sharing again.

**Review by larsdouweschuitema — APPROVED** [review]

**Review by jpsc — APPROVED** [review]
👍

**Comment by jpsc** [comment]
> There is a nice tool which reduces size of SVG: [jakearchibald.github.io/svgomg](https://jakearchibald.github.io/svgomg/)
> Maybe you already used it, but it can't hurt sharing again.

We have that already automated.

https://github.com/funda-frontend/icons/blob/af7c208a0bec4b95f8d0cd9f39a1bdd9eed1d826/package.json#L42-L52

**Pull request merged**
